import { request } from '@/utils'

export const businessApi = {
  dictionaries: {
    list: (params, options = {}) => request.get('/dictionary-items', { params, ...options }),
    definitions: () => request.get('/dictionary-items/definitions'),
    create: data => request.post('/dictionary-items', data),
    update: data => request.patch(`/dictionary-items/${data.id}`, data),
    delete: id => request.delete(`/dictionary-items/${id}`),
  },
  clients: {
    page: params => request.get('/clients', { params }),
    options: params => request.get('/clients/options', { params }),
    create: data => request.post('/clients', data),
    update: (id, data) => request.patch(`/clients/${id}`, data),
    changeIdentity: (id, data) => request.patch(`/clients/${id}/identity`, data),
    delete: id => request.delete(`/clients/${id}`),
    detail: id => request.get(`/clients/${id}`),
    contacts: clientId => request.get(`/clients/${clientId}/contacts`),
    createContact: (clientId, data) => request.post(`/clients/${clientId}/contacts`, data),
    updateContact: (clientId, contactId, data) => request.patch(`/clients/${clientId}/contacts/${contactId}`, data),
    identityHistories: clientId => request.get(`/clients/${clientId}/identity-histories`),
    mergeLogs: clientId => request.get(`/clients/${clientId}/merge-logs`),
    merge: (clientId, data) => request.post(`/clients/${clientId}/merge`, data),
    revertMerge: (clientId, logId) => request.post(`/clients/${clientId}/merge-logs/${logId}/revert`),
    credentials: clientId => request.get(`/clients/${clientId}/credentials`),
    credentialSystemOptions: () => request.get('/clients/credential-system-options'),
    createCredential: (clientId, data) => request.post(`/clients/${clientId}/credentials`, data),
    updateCredential: (clientId, credentialId, data) => request.patch(`/clients/${clientId}/credentials/${credentialId}`, data),
    deleteCredential: (clientId, credentialId) => request.delete(`/clients/${clientId}/credentials/${credentialId}`),
    recordCredentialCopy: (clientId, credentialId, field) => request.post(`/clients/${clientId}/credentials/${credentialId}/copy-log`, { field }),
    importBatches: params => request.get('/clients/imports', { params }),
    importUnitDirectory: data => request.post('/clients/imports/unit-directory', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000,
    }),
    importAssetReportControl: data => request.post('/clients/imports/asset-report-control', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000,
    }),
    importIntegrationValueAdded: data => request.post('/clients/imports/integration-value-added', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000,
    }),
    importBatchDetail: (batchId, params) => request.get(`/clients/imports/${batchId}`, { params }),
    importableRowIds: batchId => request.get(`/clients/imports/${batchId}/importable-row-ids`),
    revalidateImportBatch: batchId => request.post(`/clients/imports/${batchId}/revalidate`),
    confirmImportBatch: (batchId, data) => request.post(`/clients/imports/${batchId}/confirm`, data),
    deleteImportBatch: batchId => request.delete(`/clients/imports/${batchId}`),
  },
  serviceCatalog: {
    list: params => request.get('/service-catalog', { params }),
    create: data => request.post('/service-catalog', data),
    update: (id, data) => request.patch(`/service-catalog/${id}`, data),
    delete: id => request.delete(`/service-catalog/${id}`),
  },
  announcements: {
    page: params => request.get('/announcements', { params }),
    active: params => request.get('/announcements/active', { params }),
    create: data => request.post('/announcements', data),
    update: (id, data) => request.patch(`/announcements/${id}`, data),
    delete: id => request.delete(`/announcements/${id}`),
  },
  orders: {
    page: params => request.get('/orders', { params }),
    detail: id => request.get(`/orders/${id}`),
    create: data => request.post('/orders', data),
    update: (id, data) => request.patch(`/orders/${id}`, data),
    delete: (id, data) => request.delete(`/orders/${id}`, { data }),
    renewServiceItem: (orderId, itemId) => request.post(`/orders/${orderId}/service-items/${itemId}/renew`),
  },
  finance: {
    summary: () => request.get('/finance/summary'),
    contracts: params => request.get('/finance/contracts', { params }),
    contractDetail: id => request.get(`/finance/contracts/${id}`),
    createContract: data => request.post('/finance/contracts', data),
    updateContract: (id, data) => request.patch(`/finance/contracts/${id}`, data),
    invoices: params => request.get('/finance/invoices', { params }),
    invoiceDetail: id => request.get(`/finance/invoices/${id}`),
    createInvoice: data => request.post('/finance/invoices', data),
    updateInvoice: (id, data) => request.patch(`/finance/invoices/${id}`, data),
    payments: params => request.get('/finance/payments', { params }),
    paymentDetail: id => request.get(`/finance/payments/${id}`),
    createPayment: data => request.post('/finance/payments', data),
    updatePayment: (id, data) => request.patch(`/finance/payments/${id}`, data),
    matchPayment: (id, data) => request.post(`/finance/payments/${id}/matches`, data),
    importBankStatement: data => request.post('/finance/payments/imports/bank-statement', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 60000,
    }),
    paymentImportBatches: params => request.get('/finance/payments/imports', { params }),
    paymentImportDetail: (batchId, params) => request.get(`/finance/payments/imports/${batchId}`, { params }),
    confirmPaymentImport: (batchId, data) => request.post(`/finance/payments/imports/${batchId}/confirm`, data),
  },
  archive: {
    summary: () => request.get('/archive/summary'),
    linkTargets: params => request.get('/archive/link-targets', { params }),
    attachments: params => request.get('/archive/attachments', { params }),
    uploadAttachment: data => request.post('/archive/attachments', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 300000,
    }),
    previewAttachment: id => request.get(`/archive/attachments/${id}/preview`, { responseType: 'blob', timeout: 300000 }),
    downloadAttachment: id => request.get(`/archive/attachments/${id}/download`, { responseType: 'blob', timeout: 300000 }),
    deleteAttachment: id => request.delete(`/archive/attachments/${id}`),
    materials: params => request.get('/archive/materials', { params }),
    createMaterial: data => request.post('/archive/materials', data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 300000,
    }),
    updateMaterial: (id, data) => request.patch(`/archive/materials/${id}`, data, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 300000,
    }),
    deleteMaterial: id => request.delete(`/archive/materials/${id}`),
    weeklyReports: params => request.get('/archive/weekly-reports', { params }),
    createWeeklyReport: data => request.post('/archive/weekly-reports', data),
    updateWeeklyReport: (id, data) => request.patch(`/archive/weekly-reports/${id}`, data),
    generateWeeklyDraft: data => request.post('/archive/weekly-reports/generate-draft', data),
    submitWeeklyReport: id => request.post(`/archive/weekly-reports/${id}/submit`),
    withdrawWeeklyReport: id => request.post(`/archive/weekly-reports/${id}/withdraw`),
    deleteWeeklyReport: id => request.delete(`/archive/weekly-reports/${id}`),
  },
  kdocs: {
    historyLinks: () => request.get('/kdocs/history/links'),
  },
  commission: {
    rules: params => request.get('/commission/rules', { params }),
    createRule: data => request.post('/commission/rules', data),
    updateRule: (id, data) => request.patch(`/commission/rules/${id}`, data),
    deleteRule: id => request.delete(`/commission/rules/${id}`),
    settlementItems: params => request.get('/commission/settlement-items', { params }),
    settlements: params => request.get('/commission/settlements', { params }),
    settlementDetail: id => request.get(`/commission/settlements/${id}`),
    lines: params => request.get('/commission/lines', { params }),
    generateDraft: data => request.post('/commission/settlements/generate-draft', data),
    recalculateSettlement: id => request.post(`/commission/settlements/${id}/recalculate`),
    confirmSettlement: id => request.post(`/commission/settlements/${id}/confirm`),
    markPaid: id => request.post(`/commission/settlements/${id}/mark-paid`),
    cancelSettlement: id => request.post(`/commission/settlements/${id}/cancel`),
  },
  dashboard: {
    overview: params => request.get('/dashboard/overview', { params }),
    workbench: params => request.get('/dashboard/workbench', { params }),
  },
  operationLogs: {
    page: params => request.get('/operation-logs', { params }),
    options: () => request.get('/operation-logs/options'),
  },
  organization: {
    summary: () => request.get('/organization/summary'),
    departments: () => request.get('/organization/departments'),
    departmentOptions: () => request.get('/organization/departments/options'),
    createDepartment: data => request.post('/organization/departments', data),
    updateDepartment: (id, data) => request.patch(`/organization/departments/${id}`, data),
    deleteDepartment: id => request.delete(`/organization/departments/${id}`),
  },
  serviceItems: {
    page: params => request.get('/service-items', { params }),
  },
  employees: {
    list: () => request.get('/employees'),
  },
  team: {
    page: params => request.get('/team', { params }),
    summary: () => request.get('/team/summary'),
    updateProfile: (id, data) => request.patch(`/team/${id}/profile`, data),
  },
}
